Dev
synapsecns/sdk pull request #7
Opened 2021-12-14 21:15 UTC by BlazeWasHere

2021-12-15 23:43 UTC, maozdror commented on test/bridge/slippages-test.ts
> +// BEFORE: :file:`src/bridge/slippages.ts`
@BlazeWasHere in general, try to strip stuff like this out before a merge

2021-12-15 23:46 UTC, maozdror requested changes

2021-12-15 23:46 UTC, maozdror commented on test/bridge/slippages-test.ts
> +import { BigNumber } from "ethers";
Nitpick: I like to enforce explicit ethers imports for any/all things; `BigNumber` should be imported from `@ethersproject/bignumber`

2021-12-15 23:46 UTC, maozdror commented on test/bridge/slippages-test.ts
> +// BEFORE: :file:`src/bridge/slippages.ts`
@BlazeWasHere in general, try to strip stuff like this out before a merge

2021-12-15 23:50 UTC, maozdror commented on test/bridge/slippages-test.ts
> +// BEFORE: :file:`src/bridge/slippages.ts`
Rather, while I'd prefer it not be in _code_ files, I do not mind -- actually, I highly encourage it -- if you put coverage details in a different file at the same level as the coverage-checked file.

2021-12-16 00:32 UTC, maozdror commented
@BlazeWasHere also, make sure to rebase your branch -- just pushed a tiny change on main dev branch

2021-12-16 07:11 UTC, BlazeWasHere commented
> @BlazeWasHere also, make sure to rebase your branch -- just pushed a tiny change on main dev branch

There shouldn't be any merge conflicts now.

2021-12-17 21:25 UTC, merged